[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"

[blobs]
  # Active Netlify Blobs (rien d'autre à faire)
