[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"

[blobs]
  # Active Netlify Blobs
